### ISSUE TITLE
Crystal Linker Issue

### ISSUE THREAD

**Issue by Dongsuccer** [kjmaster1/MagicBooks#10]
I probably accidentally clicked something with the crystal linker and now I can't select crystals to link to my mana infuser. I tried destroying all the crystals and replacing them as well as making a new crystal infuser and nothing worked. plz help

**Comment by kjmaster1** [comment]
If you can remember where you placed your last crystal then go to those coords and try linking a crystal at that position. If that doesn't work then craft another crystal linker and use that one.

**Comment by Dongsuccer** [comment]
I put another crystal very far away and tried to connect it and that reset
the connection, thank you.
