### ISSUE TITLE
[Request] Reduce default ore spawn rate and dungeon loot

### ISSUE THREAD

**Issue by xenoflot** [kjmaster1/MagicBooks#13]
Hi,

Per the subject, I'd like to request that the default ore spawn rate and dungeon loot rates are toned down by an order of magnitude. 

As a tech-leaning player, I don't get into magic mods much and the MB crystals are clogging my inventory. Perhaps reduce the rate to something similar to diamonds or gold? That will have an added bonus of making a find even more rewarding.

Secondly, I find multiple books from MagicBooks in every dungeon chest. E.g. I just found a 2-chest dungeon and between them have: 4 earth books, 4 fire books, 5 air books and 6 water books. I'm not sure how many books are required for playing the mod, but I'm sure it's not that many :D I don't know how dungeon loot works but if your books are taking the place of items from other mods, that's another good reason to tone it down.

Cheers!

**Comment by kjmaster1** [comment]
Both ore generation and books in dungeons have been reduced. Thank you for the request.

**Comment by xenoflot** [comment]
Great!
