### ISSUE TITLE
crash on server startup(1.12)

### ISSUE THREAD

**Issue by SDUBZ** [kjmaster1/MagicBooks#4]
Forge: 1.12-2413
magic books: MagicBooks-1.1.2 (1.12)

crash report:
[crash-2017-07-18_18.15.08-server.txt](https://github.com/kjmaster1/MagicBooks/files/1155169/crash-2017-07-18_18.15.08-server.txt)

**Comment by kjmaster1** [comment]
This has now been fixed and a patch version will be released shortly, thank you for the report.
