### ISSUE TITLE
[Suggestion] Do Away With Keybinds

### ISSUE THREAD

**Issue by MokahTGS** [kjmaster1/MagicBooks#5]
My suggestion is to change the casting of spells from keybinds to some sort of spell book UI or item.  Keybinds are fine if you only use this or a couple mods, but if you use any modpack of decent size you quickly run out of keys to bind too.  This mod is already using 8 keys and I'm sure you have more spells planed.  It will only get worse.

Perhaps the player could make a staff or wand for each element that you unlock spells.  Then the player could shift-click the wand to change the active spell on the wand.  This completely fees you from the keybind issue and gives you something cool to fling spells with.

**Comment by kjmaster1** [comment]
In the future a staff will be implemented into the mod. The keybinds are definitely just a temporary thing to allow players to still cast spells while I work out a good casting system. Thank you for the suggestion :)

**Comment by kjmaster1** [comment]
Most keybinds removed through the implementation of the 'Magic Book'
